name: gasandelec-Guildford
favicon: null
layout_spectrum: 0.7447145548649132
typography_spectrum: 0.19767355010844767
title: Gas and Electricity Testing on 01483 697037  in Guildford www.gasandelec.net
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75121389-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dbd8e9'
    - '#9ba2d9'
    - '#3b4fc0'
    - '#ac8170'
  brandStrength: 0.057120593497529626
  lightness: 0.813450226560235
  saturation: 0.44789935019798577
  rhythmicContrast: 0.7027711123228073
purpose: []
